apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: simple-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # External port on each node
  type: NodePort
