apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # This must match the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80  # Exposed Service port
      targetPort: 80  # Container port
  type: ClusterIP  # Default (internal service)
