apiVersion: apps/v1
kind: Deployment
metadata:
  name: efficient-cloud-solution
spec:
  replicas: 3
  selector:
    matchLabels:
      app: efficient-cloud-solution
  template:
    metadata:
      labels:
        app: efficient-cloud-solution
    spec:
      containers:
      - name: efficient-cloud-solution
        image: efficient-cloud-solution:v1.0.0
        ports:
        - containerPort: 5000