apiVersion: v1
kind: Service
metadata:
  name: efficient-cloud-solution
spec:
  selector:
    app: efficient-cloud-solution
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer