apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-team-a
  namespace: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-team-a
  template:
    metadata:
      labels:
        app: nginx-team-a
    spec:
      containers:
        - name: nginx
          image: nginx
    