apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gymapp-deployment
  name: gymapp-deployment
  annotations:
    info: "hkabra Deployment"
    email: "hkabra1979@gmail.com"
    owner: "hkabra"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gymapp
  template:
    metadata:
      labels:
        app: gymapp
    spec:
      containers:
        - name: gymapp-container
          image: hkabra/gymapp
          ports:
            - containerPort: 80
